### ISSUE TITLE
How to use this in storybook or E2E tests

### ISSUE THREAD

**Issue by srlee309** [jscutlery/test-utils#2]
I am getting the below error when I try to run this with a storybook test.

"Error: zone-testing.js is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone-testing.js".

If it cannot be used in storybook/E2E tests, can you please update the documentation to say this or if it can can you please add some information to describe how to get it working.

To reproduce the error:

- Clone https://github.com/srlee309/component-commands-example
- Run: ng run storybook-example-form:storybook-e2e

This is the spec that is failing.
https://github.com/srlee309/component-commands-example/blob/master/libs/example/form/.cypress/src/integration/storybook/form-component-test-harness.spec.ts

import '@jscutlery/cypress-harness/support'; is in the index.
https://github.com/srlee309/component-commands-example/blob/master/libs/example/form/.cypress/src/support/index.ts

**Comment by yjaaidi** [comment]
Hi @srlee309! Thank you for the feedback.
There is in fact an issue with `@jscutlery/cypress-harness` when used to test an application instead of a single component with `@jscutlery/cypress-mount`.

Apparently, this happens because:
1. `@jscutlery/cypress-harness` depends on `@angular/cdk/testing`'s `UnitTestComponent` (Cf. https://github.com/angular/components/blob/5cc960157a3260c90bfd7e5f442d7979c577605c/src/cdk/testing/testbed/unit-test-element.ts) 
2. `@angular/cdk/testing` imports `@angular/core/testing` which in its turn imports `before_each.ts` that contains the following side effect:
https://github.com/angular/angular/blob/a6971ba89adc253bfa4260036ee4a1e0bd76159f/packages/core/testing/src/before_each.ts#L23-L28
that tries to reset fake async zones while we are not even using fake async zones.

We'll be providing a fix soon but meanwhile, here's a workaround; you can add the following code to your `support/index.ts`:
```ts
import 'zone.js/dist/zone';
/* @hack fixes "Mocha has already been patched with Zone" error. */
(globalThis as any)['Mocha']['__zone_patch__'] = false; 
import 'zone.js/dist/zone-testing';
```

Thank you for detecting this issue. Please, let us know if this works for you.

**Comment by yjaaidi** [comment]
v0.2.0 has been published with the fix
