### ISSUE TITLE
Tailwind styles support

### ISSUE THREAD

**Issue by simoneatum** [jscutlery/test-utils#62]
Hi,

First of all thank you very much for you work on this package!

I'm opening this issue cause i wasn't able to make tailwind works when mounting the component inside an nx library.

I tried importing a css file with tailwind imports like that:
```
import { Component } from '@angular/core';
import { mount } from '@jscutlery/cypress-angular/mount';

@Component({
  template: `<h1 class="bg-red-500 text-red-500">👋 Hello!</h1>`,
})
export class GreetingsComponent {}

describe('greetings', () => {
  it('should say hello', () => {
    mount(GreetingsComponent, {
      cssFile: 'cypress/support/base-style.css',
    });
    cy.get('h1').contains('👋 Hello!');
  });
});
```
or importing tailwind styles using the inline style property:
```
import { Component } from '@angular/core';
import { mount } from '@jscutlery/cypress-angular/mount';

@Component({
  template: `<h1 class="bg-red-500 text-red-500">👋 Hello!</h1>`,
})
export class GreetingsComponent {}

describe('greetings', () => {
  it('should say hello', () => {
    mount(GreetingsComponent, {
      style: `@tailwind base;
      @tailwind components;
      @tailwind utilities;
      `,
    });
    cy.get('h1').contains('👋 Hello!');
  });
});
```

Is it possible to make it works?

Thank you

**Comment by edbzn** [comment]
Hello, I never used Tailwind so I don't know exactly how it works but using the `cssFile` property you can load your css relatively to the `fileServerFolder` value defined in your Cypress configuration, here is an example serving a [demo file](https://github.com/jscutlery/test-utils/blob/ff3d695892f41d67b38c0873392b4d4b270de71a/packages/cypress-mount-integration/src/components/mount.spec.ts#L70). I'm not sure it will work since Tailwind uses post-processing tools like PostCSS, let us know. Regarding the inline method, it does not look like regular css, it will also need post-processing. Maybe the ability to extend the Webpack configuration would allow it (#60).

**Comment by simoneatum** [comment]
Hi, thank you for the fast reply.
At the end I used a workaround, i simply compiled a css file using tailwindcss-cli and loaded the compiled file with the cssFile option.
